'use client';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {money,pct} from '@/lib/utils';
export const palette=['#138c78','#4667d5','#91afc5','#ce9c45','#8d75be','#c17180','#4a8aab','#799857'];
const chartStyle={background:'var(--surface)',border:'1px solid var(--border)',borderRadius:12,fontSize:14,color:'var(--text)',boxShadow:'0 6px 24px #00000015'};
export function Sparkline({values,color='#138c78'}:{values:number[];color?:string}){const data=values.filter(Number.isFinite),min=Math.min(...data),max=Math.max(...data);const points=data.map((v,i)=>`${3+i/Math.max(1,data.length-1)*80},${max===min?18:32-(v-min)/(max-min)*28}`).join(' ');return <div className="sparkline" aria-hidden="true"><svg viewBox="0 0 86 36" width="100%" height="100%"><polyline points={points} fill="none" stroke={color} strokeWidth="2" strokeLinejoin="round" strokeLinecap="round"/></svg></div>;}
export function CashChart({data,annual=false,unit='money'}:{data:Record<string,number|string|null>[];annual?:boolean;unit?:string}){
 const format=(v:any)=>unit==='percent'?pct(Number(v)):unit==='capita'?money(Number(v),false):money(Number(v));
 return <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:12,right:12,left:6,bottom:5}}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#138c78" stopOpacity={.15}/><stop offset="100%" stopColor="#138c78" stopOpacity={0}/></linearGradient><linearGradient id="expenseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4667d5" stopOpacity={.09}/><stop offset="100%" stopColor="#4667d5" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="label" tick={{fontSize:12,fill:'var(--muted)'}} axisLine={false} tickLine={false} minTickGap={16}/><YAxis width={unit==='capita'?64:55} tickFormatter={v=>unit==='percent'?`${v}%`:unit==='capita'?`${Math.round(v/1000)} tis.`:`${v/1e6}`} tick={{fontSize:12,fill:'var(--muted)'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartStyle} formatter={format} labelFormatter={v=>`${annual?'Rok':'Období'} ${v}`}/><Area type="linear" dataKey="income" name="Příjmy" stroke="#138c78" strokeWidth={2.5} fill="url(#incomeFill)" dot={{r:3,strokeWidth:2,fill:'var(--surface)'}} activeDot={{r:5}} isAnimationActive={false}/><Area type="linear" dataKey="expense" name="Výdaje" stroke="#4667d5" strokeWidth={2.5} fill="url(#expenseFill)" dot={{r:3,strokeWidth:2,fill:'var(--surface)'}} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>;
}
export function MetricChart({data,unit='money',bar=false}:{data:{label:string;value:number|null}[];unit?:string;bar?:boolean}){
 const common=<><CartesianGrid stroke="var(--border)" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="label" tick={{fontSize:12,fill:'var(--muted)'}} axisLine={false} tickLine={false} minTickGap={12}/><YAxis width={60} tickFormatter={v=>unit==='percent'?`${v}%`:unit==='capita'?`${Math.round(v/1000)} tis.`:`${v/1e6}`} tick={{fontSize:12,fill:'var(--muted)'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartStyle} formatter={(v:any)=>unit==='percent'?pct(Number(v)):money(Number(v),unit!=='capita')}/><ReferenceLine y={0} stroke="var(--border)"/></>;
 return <div className="chart-container"><ResponsiveContainer width="100%" height="100%">{bar?<BarChart data={data} margin={{right:10,top:10}}>{common}<Bar dataKey="value" name="Hodnota" fill="#138c78" radius={[5,5,0,0]} isAnimationActive={false}/></BarChart>:<LineChart data={data} margin={{right:10,top:10}}>{common}<Line type="linear" dataKey="value" name="Hodnota" stroke="#138c78" strokeWidth={2.5} dot={{r:4,strokeWidth:2,fill:'var(--surface)'}} isAnimationActive={false} connectNulls={false}/></LineChart>}</ResponsiveContainer></div>;
}
export function BudgetChart({data}:{data:{name:string;approved:number;amended:number;actual:number}[]}){return <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:12,right:10,left:5}}><CartesianGrid stroke="var(--border)" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="name" tick={{fontSize:13,fill:'var(--muted)'}} tickLine={false} axisLine={false}/><YAxis width={55} tickFormatter={v=>String(v/1e6)} tick={{fontSize:12,fill:'var(--muted)'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartStyle} formatter={(v:any)=>money(Number(v))}/><Bar dataKey="approved" name="Schválený" fill="#c7d3df" radius={[4,4,0,0]} isAnimationActive={false}/><Bar dataKey="amended" name="Upravený" fill="#4667d5" radius={[4,4,0,0]} isAnimationActive={false}/><Bar dataKey="actual" name="Skutečnost" fill="#138c78" radius={[4,4,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;}
export function HorizontalChart({data,onSelect}:{data:{name:string;value:number;code:string}[];onSelect:(code:string)=>void}){return <div style={{height:Math.max(260,data.length*42)}}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{left:5,right:40}}><CartesianGrid stroke="var(--border)" horizontal={false} strokeDasharray="3 5"/><XAxis type="number" tickFormatter={v=>`${v/1e6}`} tick={{fontSize:12,fill:'var(--muted)'}} axisLine={false} tickLine={false}/><YAxis dataKey="name" type="category" width={175} tick={{fontSize:12,fill:'var(--muted)'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartStyle} formatter={(v:any)=>money(Number(v))}/><Bar dataKey="value" name="Skutečnost" radius={[0,4,4,0]} isAnimationActive={false} onClick={(r:any)=>onSelect(r.code)} cursor="pointer">{data.map((r,i)=><Cell key={r.code} fill={palette[i%palette.length]}/>)}</Bar></BarChart></ResponsiveContainer></div>;}
